version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Deploy to Baota Server
          command: |
            ssh admin@8.130.51.110 "mkdir -p /www/wwwroot/myapp"
            scp -r ./* admin@8.130.51.110:/www/wwwroot/myapp
workflows:
  version: 2
  deploy:
    jobs:
      - deploy